### ISSUE TITLE
Yarn error on Mac Silicon

### ISSUE THREAD

**Issue by michielvaneerd** [tidepool-org/uploader#1497]
Hi,
I've cloned the repository, did a `nvm use 12.13.0` and after that executed the `yarn` command, but I'm getting the following error:

```
yarn install v1.22.18
[1/4] 🔍  Resolving packages...
warning Resolution field "charm@1.0.2" is incompatible with requested version "charm@0.1.x"
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > connected-react-router@6.8.0" has unmet peer dependency "immutable@^3.8.1 || ^4.0.0-rc.1".
warning " > connected-react-router@6.8.0" has unmet peer dependency "react-router@^4.3.1 || ^5.0.0".
warning " > connected-react-router@6.8.0" has unmet peer dependency "seamless-immutable@^7.1.3".
warning " > @babel/eslint-parser@7.12.1" has incorrect peer dependency "eslint@>=7.5.0".
warning " > @babel/eslint-plugin@7.12.1" has incorrect peer dependency "eslint@>=7.5.0".
warning " > eslint-config-airbnb@18.2.1" has unmet peer dependency "eslint-plugin-react-hooks@^4 || ^3 || ^2.3.0 || ^1.7.0".
warning "eslint-plugin-jest > @typescript-eslint/experimental-utils > @typescript-eslint/typescript-estree > tsutils@3.17.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
warning abbrev@1.1.0: Invalid bin field for "abbrev".
warning ansicolors@0.3.2: Invalid bin field for "ansicolors".
warning ansistyles@0.1.3: Invalid bin field for "ansistyles".
warning archy@1.0.0: Invalid bin field for "archy".
warning call-limit@1.1.0: Invalid bin field for "call-limit".
warning bluebird@3.5.0: Invalid bin field for "bluebird".
warning chownr@1.0.1: Invalid bin field for "chownr".
warning cmd-shim@2.0.2: Invalid bin field for "cmd-shim".
warning columnify@1.5.4: Invalid bin field for "columnify".
warning config-chain@1.1.11: Invalid bin field for "config-chain".
warning debuglog@1.0.1: Invalid bin field for "debuglog".
warning detect-indent@5.0.0: Invalid bin field for "detect-indent".
warning dezalgo@1.0.3: Invalid bin field for "dezalgo".
warning editor@1.0.0: Invalid bin field for "editor".
warning fs-vacuum@1.2.10: Invalid bin field for "fs-vacuum".
warning fs-write-stream-atomic@1.0.10: Invalid bin field for "fs-write-stream-atomic".
warning fstream@1.0.11: Invalid bin field for "fstream".
warning graceful-fs@4.1.11: Invalid bin field for "graceful-fs".
warning has-unicode@2.0.1: Invalid bin field for "has-unicode".
warning iferr@0.1.5: Invalid bin field for "iferr".
warning imurmurhash@0.1.4: Invalid bin field for "imurmurhash".
warning inflight@1.0.6: Invalid bin field for "inflight".
warning inherits@2.0.3: Invalid bin field for "inherits".
warning ini@1.3.4: Invalid bin field for "ini".
warning init-package-json@1.10.1: Invalid bin field for "init-package-json".
warning lazy-property@1.0.0: Invalid bin field for "lazy-property".
warning lockfile@1.0.3: Invalid bin field for "lockfile".
warning lodash._baseindexof@3.1.0: Invalid bin field for "lodash._baseindexof".
warning lodash._baseuniq@4.6.0: Invalid bin field for "lodash._baseuniq".
warning lodash._bindcallback@3.0.1: Invalid bin field for "lodash._bindcallback".
warning lodash._cacheindexof@3.0.2: Invalid bin field for "lodash._cacheindexof".
warning lodash._createcache@3.1.2: Invalid bin field for "lodash._createcache".
warning lodash._getnative@3.9.1: Invalid bin field for "lodash._getnative".
warning lodash.clonedeep@4.5.0: Invalid bin field for "lodash.clonedeep".
warning lodash.restparam@3.6.1: Invalid bin field for "lodash.restparam".
warning lodash.union@4.6.0: Invalid bin field for "lodash.union".
warning lodash.uniq@4.5.0: Invalid bin field for "lodash.uniq".
warning lodash.without@4.4.0: Invalid bin field for "lodash.without".
warning mississippi@1.3.0: Invalid bin field for "mississippi".
warning move-concurrently@1.0.1: Invalid bin field for "move-concurrently".
warning npm-cache-filename@1.0.2: Invalid bin field for "npm-cache-filename".
warning npm-install-checks@3.0.0: Invalid bin field for "npm-install-checks".
warning once@1.4.0: Invalid bin field for "once".
warning osenv@0.1.4: Invalid bin field for "osenv".
warning path-is-inside@1.0.2: Invalid bin field for "path-is-inside".
warning promise-inflight@1.0.1: Invalid bin field for "promise-inflight".
warning read@1.0.7: Invalid bin field for "read".
warning read-cmd-shim@1.0.1: Invalid bin field for "read-cmd-shim".
warning read-installed@4.0.3: Invalid bin field for "read-installed".
warning readdir-scoped-modules@1.0.2: Invalid bin field for "readdir-scoped-modules".
warning retry@0.10.1: Invalid bin field for "retry".
warning sha@2.0.1: Invalid bin field for "sha".
warning slide@1.1.6: Invalid bin field for "slide".
warning sorted-object@2.0.1: Invalid bin field for "sorted-object".
warning sorted-union-stream@2.1.3: Invalid bin field for "sorted-union-stream".
warning tar@2.2.1: Invalid bin field for "tar".
warning text-table@0.2.0: Invalid bin field for "text-table".
warning uid-number@0.0.6: Invalid bin field for "uid-number".
warning umask@1.1.0: Invalid bin field for "umask".
warning unique-filename@1.1.0: Invalid bin field for "unique-filename".
warning unpipe@1.0.0: Invalid bin field for "unpipe".
warning validate-npm-package-license@3.0.1: Invalid bin field for "validate-npm-package-license".
warning validate-npm-package-name@3.0.0: Invalid bin field for "validate-npm-package-name".
warning wrappy@1.0.2: Invalid bin field for "wrappy".
[4/4] 🔨  Building fresh packages...
$ concurrently "electron-builder install-app-deps" "node node_modules/fbjs-scripts/node/check-dev-engines.js package.json"
[0]   • electron-builder  version=22.9.1
[1] node node_modules/fbjs-scripts/node/check-dev-engines.js package.json exited with code 0
[0]   • installing production dependencies  platform=darwin arch=x64 appDir=/Users/michielve/Documents/web/uploader/app
[0]   ⨯ /Users/michielve/.nvm/versions/node/v12.22.12/bin/node exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
[0] Output:
[0] 
[0] Output:
yarn install v1.22.18
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[0] 
[0] Error output:
[0] 
[0] Error output:
error /Users/michielve/Documents/web/uploader/app/node_modules/@ronomon/direct-io: Command failed.
[0] Exit code: 1
[0] Command: node-gyp rebuild
[0] Arguments: 
[0] Directory: /Users/michielve/Documents/web/uploader/app/node_modules/@ronomon/direct-io
[0] Output:
[0] gyp info it worked if it ends with ok
[0] gyp info using node-gyp@9.0.0
[0] gyp info using node@12.22.12 | darwin | x64
[0] gyp info find Python using Python version 3.8.9 found at "/Applications/Xcode.app/Contents/Developer/usr/bin/python3"
[0] gyp info spawn /Applications/Xcode.app/Contents/Developer/usr/bin/python3
[0] gyp info spawn args [
[0] gyp info spawn args   '/Users/michielve/.nvm/versions/node/v12.22.12/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
[0] gyp info spawn args   'binding.gyp',
[0] gyp info spawn args   '-f',
[0] gyp info spawn args   'make',
[0] gyp info spawn args   '-I',
[0] gyp info spawn args   '/Users/michielve/Documents/web/uploader/app/node_modules/@ronomon/direct-io/build/config.gypi',
[0] gyp info spawn args   '-I',
[0] gyp info spawn args   '/Users/michielve/.nvm/versions/node/v12.22.12/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
[0] gyp info spawn args   '-I',
[0] gyp info spawn args   '/Users/michielve/.electron-gyp/8.5.3/include/node/common.gypi',
[0] gyp info spawn args   '-Dlibrary=shared_library',
[0] gyp info spawn args   '-Dvisibility=default',
[0] gyp info spawn args   '-Dnode_root_dir=/Users/michielve/.electron-gyp/8.5.3',
[0] gyp info spawn args   '-Dnode_gyp_dir=/Users/michielve/.nvm/versions/node/v12.22.12/lib/node_modules/npm/node_modules/node-gyp',
[0] gyp info spawn args   '-Dnode_lib_file=/Users/michielve/.electron-gyp/8.5.3/<(target_arch)/node.lib',
[0] gyp info spawn args   '-Dmodule_root_dir=/Users/michielve/Documents/web/uploader/app/node_modules/@ronomon/direct-io',
[0] gyp info spawn args   '-Dnode_engine=v8',
[0] gyp info spawn args   '--depth=.',
[0] gyp info spawn args   '--no-parallel',
[0] gyp info spawn args   '--generator-output',
[0] gyp info spawn args   'build',
[0] gyp info spawn args   '-Goutput_dir=.'
[0] gyp info spawn args ]
[0] gyp: name 'openssl_fips' is not defined while evaluating condition 'openssl_fips != ""' in binding.gyp while trying to load binding.gyp
[0] gyp ERR! configure error 
[0] gyp ERR! stack Error: `gyp` failed with exit code: 1
[0] gyp ERR! stack     at ChildProcess.onCpExit (/Users/michielve/.nvm/versions/node/v12.22.12/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:261:16)
[0] gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
[0] gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
[0] gyp ERR! System Darwin 21.4.0
[0] gyp ERR! command "/Users/michielve/.nvm/versions/node/v12.22.12/bin/node" "/Users/michielve/.nvm/versions/node/v12.22.12/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
[0] gyp ERR! cwd /Users/michielve/Documents/web/uploader/app/node_modules/@ronomon/direct-io
[0] gyp ERR! node -v v12.22.12
[0] gyp ERR! node-gyp -v v9.0.0
[0] gyp ERR! not ok
[0]   stackTrace=
```

After this the following error:

```
Error: /Users/michielve/.nvm/versions/node/v12.22.12/bin/node exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
```

I've searched the issues and on StackOverflow but I cannot solve this.

Does someone has an idea what could be the cause?

**Comment by krystophv** [comment]
It would seem that the version of `electron-builder` currently relied upon by the uploader (`22.9.1`) doesn't have support for the M1 (arm-based) macs. You may have luck updating the dependency. There are some people running into similar problems with some solutions here: https://github.com/electron-userland/electron-builder/issues/5392
