### ISSUE TITLE
npm install failing

### ISSUE THREAD

**Issue by jlecount** [tidepool-org/uploader#1500]
Sorry if this is user error, but I've been trying to do a local setup per the README and am getting the following erorrs on post-install:

```
5243 info lifecycle tidepool-uploader@2.45.1~postinstall: tidepool-uploader@2.45.1
5244 verbose lifecycle tidepool-uploader@2.45.1~postinstall: unsafe-perm in lifecycle true
5245 verbose lifecycle tidepool-uploader@2.45.1~postinstall: PATH: /home/jlecount/.nvm/versions/node/v12.22.12/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/jlecount/code/third-party/uploader/node_modules/.bin:/home/jlecount/.sdkman/candidates/scala/current/bin:/home/jlecount/.sdkman/candidates/sbt/current/bin:/home/jlecount/.nvm/versions/node/v12.22.12/bin:/home/linuxbrew/.linuxbrew/opt/postgresql@10/bin:/usr/local/go/bin:/home/jlecount/go:/usr/local/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/snap/bin:/home/jlecount/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/jlecount/code/personal/zsh-git-prompt/src/.bin:/home/jlecount/.yarn/bin:/home/jlecount/code/third-party/uploader/node_modules/.bin
5246 verbose lifecycle tidepool-uploader@2.45.1~postinstall: CWD: /home/jlecount/code/third-party/uploader
5247 silly lifecycle tidepool-uploader@2.45.1~postinstall: Args: [
5247 silly lifecycle   '-c',
5247 silly lifecycle   'concurrently "electron-builder install-app-deps" "node node_modules/fbjs-scripts/node/check-dev-engines.js package.json"'
5247 silly lifecycle ]
5248 silly lifecycle tidepool-uploader@2.45.1~postinstall: Returned: code: 1  signal: null
5249 info lifecycle tidepool-uploader@2.45.1~postinstall: Failed to exec postinstall script
5250 verbose stack Error: tidepool-uploader@2.45.1 postinstall: `concurrently "electron-builder install-app-deps" "node node_modules/fbjs-scripts/node/check-dev-engines.js package.json"`
5250 verbose stack Exit status 1
5250 verbose stack     at EventEmitter.<anonymous> (/home/jlecount/.nvm/versions/node/v12.22.12/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
5250 verbose stack     at EventEmitter.emit (events.js:314:20)
5250 verbose stack     at ChildProcess.<anonymous> (/home/jlecount/.nvm/versions/node/v12.22.12/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
5250 verbose stack     at ChildProcess.emit (events.js:314:20)
5250 verbose stack     at maybeClose (internal/child_process.js:1022:16)
5250 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
5251 verbose pkgid tidepool-uploader@2.45.1
5252 verbose cwd /home/jlecount/code/third-party/uploader
5253 verbose Linux 5.4.0-104-generic
5254 verbose argv "/home/jlecount/.nvm/versions/node/v12.22.12/bin/node" "/home/jlecount/.nvm/versions/node/v12.22.12/bin/npm" "install"
5255 verbose node v12.22.12
5256 verbose npm  v6.14.16
5257 error code ELIFECYCLE
5258 error errno 1
5259 error tidepool-uploader@2.45.1 postinstall: `concurrently "electron-builder install-app-deps" "node node_modules/fbjs-scripts/node/check-dev-engines.js package.json"`
5259 error Exit status 1
5260 error Failed at the tidepool-uploader@2.45.1 postinstall script.
5260 error This is probably not a problem with npm. There is likely additional logging output above.
5261 verbose exit [ 1, true ]                                                                       
```

I'd be happy to improve the README if there is a missing setup step or some such if somebody could help set me right.

Thanks!

**Comment by gniezen** [comment]
Hi @jlecount ! Would you mind trying `yarn` to install the dependencies instead of `npm` and let me know your results?

**Comment by jlecount** [comment]
Hello!  Yes, that did it: `yarn install` works like a charm.  I'm now getting `could not locate the bindings file` in the .js console and trying to figure that out.  If I can't figure it out, i'll report back, but thank you!
